name: Deploy
on:
  push:
    branches: main
    paths-ignore:
      - .github/**
      - "!.github/workflows/deploy.yml"
      - .gitignore
      - LICENSE
      - README.md
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      pages: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - id: configure-pages
        uses: actions/configure-pages@v3
      - run: npm run build
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .vitepress/dist
      - id: deploy-pages
        uses: actions/deploy-pages@v2
